---
title: "College data prediction using Decision-Tree"
author: "Krishna P Koirala"
date: "6/20/2018"
output:
    md_document:
     variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(ISLR)
df <- College
```

```{r}
str(df)
```

```{r}
summary(df)
```

# Visualize data

```{r}
library(ggplot2)
ggplot(aes(Room.Board, Grad.Rate), data = df) + geom_point(aes(color = Private), size = 2, alpha = 0.6)
```

```{r}
ggplot(aes(F.Undergrad), data = df) + geom_histogram(aes(fill = Private), color = 'black', bins = 50) + theme_classic()
```

```{r}
ggplot(aes(Grad.Rate), data = df) + geom_histogram(aes(fill = Private), color = 'black', bins = 50, alpha = .5) + theme_classic()
```

```{r}
library(dplyr)
filter(df, Grad.Rate >100)
```

```{r}
df['Cazenovia College', 'Grad.Rate'] <-100
filter(df, Grad.Rate >100)
```

# Data Partition

```{r}
library(caret)
library(lattice)
set.seed(101)
trainIndex <- createDataPartition(df$Private, p = 0.7, list = FALSE)
train <- df[trainIndex,]
test <- df[-trainIndex,]
```

# Making Model

```{r}
# class is for classification. Because it can also used for regression.
library(rpart)
tree <- rpart(Private~.,method = 'class', data = train)
```

```{r}
summary(tree)
```

# Prediction of test data using model

```{r}
predicted <- predict(tree, test)
str(predicted); head(predicted)
```

# Change two columns(NO, Yes) of predicted to one single column as in train set

```{r}
sample(df$Private, 10)
sample(predicted, 10)
```


```{r}
predicted <- as.data.frame(predicted)
```

```{r}
joiner <- function(x){
    if (x >= 0.5){
        return('Yes')
    }else{
        return('No')
    }
}
```




```{r}
predicted$Private <- sapply(predicted$Yes, joiner )
```

```{r}
head(predicted)
```

# Confusion Matrix

```{r}
# From the confusion matrix we can find accuracy, recall, precision according to the business need.
table(predicted$Private, test$Private)
```

# Plot the model

```{r}
library(rpart.plot)
prp(tree)
```




